spring:
  application:
    name: personal-blog
  datasource:
    url: jdbc:mysql://localhost:3306/db_personal_blog
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html;charset=UTF-8
    suffix: .html